name: BizSvs
favicon: null
layout_spectrum: 0.74669
typography_spectrum: 1
title: 'We Make Biz Happen!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000079'
    - '#416621'
    - '#808080'
    - '#ffffff'
    - '#00ff00'
  brandStrength: 0.7303528832271695
  lightness: 0.2991939091589302
  saturation: 0.3996922308579087
  rhythmicContrast: 0.46995472232811153
purpose: []
